# Generated by Django 5.1.4 on 2025-01-27 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0003_projectphase'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_object_name', models.CharField(max_length=254, unique=True)),
                ('thickness_in', models.DecimalField(decimal_places=5, max_digits=10)),
                ('width_in', models.DecimalField(decimal_places=5, max_digits=10)),
                ('length_in', models.DecimalField(decimal_places=5, max_digits=10)),
                ('store_aisle', models.CharField(max_length=254)),
                ('store_bin', models.CharField(max_length=254)),
                ('store_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_status', models.CharField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Material statuses',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WoodSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wood_species_name', models.CharField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Wood species',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('material_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.materialobject')),
                ('material_status', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.materialstatus')),
            ],
        ),
        migrations.AddField(
            model_name='materialobject',
            name='store',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.store'),
        ),
        migrations.AddField(
            model_name='materialobject',
            name='wood_species',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.woodspecies'),
        ),
    ]
