# Generated by Django 5.1.4 on 2025-02-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialobject',
            name='length_in',
            field=models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='materialobject',
            name='store_aisle',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='materialobject',
            name='store_bin',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='materialobject',
            name='store_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='materialobject',
            name='thickness_in',
            field=models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='materialobject',
            name='width_in',
            field=models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=10, null=True),
        ),
    ]
