# Generated by Django 5.1.4 on 2025-02-06 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_alter_materialobject_length_in_and_more'),
        ('project', '0003_projectphase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
