# Generated by Django 5.1.4 on 2025-02-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_alter_material_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialobject',
            name='material_object_full_name',
            field=models.CharField(default='test', max_length=512, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialobject',
            name='material_object_name',
            field=models.CharField(max_length=254),
        ),
    ]
