# Generated by Django 5.1.4 on 2025-02-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_materialobject_material_object_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialobject',
            name='material_object_full_name',
            field=models.CharField(blank=True, default=None, max_length=512, null=True, unique=True),
        ),
    ]
