# Generated by Django 5.1.4 on 2025-01-22 15:34

import django.db.models.deletion
import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_status', models.CharField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=254, unique=True)),
                ('project_image', models.FileField(upload_to=project.models.image_name)),
                ('start_date', models.DateField(blank=True, default=None, null=True)),
                ('due_date', models.DateField(blank=True, default=None, null=True)),
                ('completed_date', models.DateField(blank=True, default=None, null=True)),
                ('depth_in', models.DecimalField(decimal_places=5, max_digits=10)),
                ('width_in', models.DecimalField(decimal_places=5, max_digits=10)),
                ('height_in', models.DecimalField(decimal_places=5, max_digits=10)),
                ('project_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projectstatus')),
            ],
        ),
    ]
