# Generated by Django 5.1.4 on 2025-01-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'verbose_name_plural': 'Project statuses'},
        ),
    ]
