# Generated by Django 5.1.4 on 2025-02-07 17:34

import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectphase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='depth_in',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='height_in',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.FileField(blank=True, default=None, null=True, upload_to=project.models.image_name),
        ),
        migrations.AlterField(
            model_name='project',
            name='width_in',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True),
        ),
    ]
