# Generated by Django 5.1.4 on 2025-01-27 18:06

import django.db.models.deletion
import note.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0003_projectphase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_date', models.DateField(default=note.models.current_date)),
                ('note', models.CharField(max_length=508)),
                ('attachment', models.FileField(upload_to=note.models.attachment_name)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
