# Generated by Django 5.1.4 on 2025-02-06 17:38

import django.db.models.deletion
import note.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
        ('project', '0003_projectphase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='attachment',
            field=models.FileField(blank=True, default=None, null=True, upload_to=note.models.attachment_name),
        ),
        migrations.AlterField(
            model_name='note',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
