# Generated by Django 5.1.4 on 2025-01-22 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0003_projectphase'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_status', models.CharField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Part statuses',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('part_name', models.CharField(max_length=254, unique=True)),
                ('rough_thickness_in', models.DecimalField(decimal_places=5, max_digits=10)),
                ('rough_width_in', models.DecimalField(decimal_places=5, max_digits=10)),
                ('rough_length_in', models.DecimalField(decimal_places=5, max_digits=10)),
                ('finished_thickness_in', models.DecimalField(decimal_places=5, max_digits=10)),
                ('finished_width_in', models.DecimalField(decimal_places=5, max_digits=10)),
                ('finished_length_in', models.DecimalField(decimal_places=5, max_digits=10)),
                ('project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project')),
                ('part_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='part.partstatus')),
            ],
        ),
    ]
