# Generated by Django 5.1.4 on 2025-01-22 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0001_initial'),
        ('project', '0003_projectphase'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='part',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='part.part'),
        ),
        migrations.AddField(
            model_name='task',
            name='phase',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projectphase'),
        ),
        migrations.AddField(
            model_name='task',
            name='step',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
